services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-admin-panel
    ports:
      - "4000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=${AUTO_SSL_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${AUTO_SSL_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${AUTO_SSL_LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=${AUTO_SSL_VIRTUAL_PORT:-3000}
    networks:
      - shop-admin
    restart: always

networks:
  shop-admin:
    driver: bridge
    name: shop-net-v1

